
samples: [
  Aspergillus_aculeatinus_CBS_121060,
  Aspergillus_aculeatus_ATCC_16872,
  Aspergillus_affinis_CMG_70,
  Aspergillus_aflatoxiformans_LH_A394,
  Aspergillus_alliaceus_CBS_536.65,
  Aspergillus_ambiguus_CBS_117.58,
  Aspergillus_amoenus_S2904,
  Aspergillus_amstelodami_NRRL_89,
  Aspergillus_annui_IBT_36122,
  Aspergillus_arachidicola_CBS_117612,
  Aspergillus_aspearensis_CBS_143672,
  Aspergillus_asperescens_NRRL_4770,
  Aspergillus_aurantiobrunneus_CBS_465.65,
  Aspergillus_austwickii_LH_A515,
  Aspergillus_avenaceus_IBT_18842,
  Aspergillus_awamori_IFM_58123,
  Aspergillus_baeticus_NRRL_62501,
  Aspergillus_bertholletiae_IBT_29228,
  Aspergillus_biplanus_NRRL_5071,
  Aspergillus_bombycis_NRRL26010,
  Aspergillus_brasiliensis_CBS_101740,
  Aspergillus_bridgeri_NRRL_13000,
  Aspergillus_brunneoviolaceus_CBS_621.78,
  Aspergillus_brunneus_CBS_112.26,
  Aspergillus_caelatus_CBS_763.97,
  Aspergillus_calidoustus_ACAL_DNA_1,
  Aspergillus_californicus_CBS_123895,
  Aspergillus_campestris_IBT_28561,
  Aspergillus_candidus_CBS_102.13,
  Aspergillus_carbonarius_ITEM_5010,
  Aspergillus_carlsbadensis_M4,
  Aspergillus_cavernicola_CBS_600.67,
  Aspergillus_cejpii_FS110,
  Aspergillus_chevalieri_M1,
  Aspergillus_clavatus_NRRL_1,
  Aspergillus_conjunctus_NRRL_5080,
  Aspergillus_coremiiformis_CBS_553.77,
  Aspergillus_costaricaensis_CBS_115574,
  #Aspergillus_costiformis_LH_A226,
  Aspergillus_creber_HOSP050413_5_135,
  Aspergillus_cristatus_EC520,
  #Aspergillus_croceus_JS3-P1,
  Aspergillus_crustosus_CBS_478.65,
  Aspergillus_cvjetkovicii_NRRL_227,
  Aspergillus_desertorum_CBS_653.73,
  Aspergillus_diversus_NRRL_5074,
  Aspergillus_egyptiacus_CBS_656.73,
  Aspergillus_elegans_IMI_345568,
  Aspergillus_ellipticus_CBS_707.79,
  Aspergillus_eucalypticola_CBS_122712,
  Aspergillus_falconensis_CBS_271.91,
  Aspergillus_felis_FM324,
  Aspergillus_fijiensis_CBS_313.89,
  Aspergillus_filifer_CBS_114510,
  Aspergillus_fischeri_NRRL_181,
  Aspergillus_flavus_NRRL_3357,
  Aspergillus_floccosus_CBS_116.37,
  Aspergillus_floridensis_IHEM_21069,
  #Aspergillus_foetidus_LH_A311,
  Aspergillus_foveolatus_CBS_279.81,
  Aspergillus_fructus_NRRL_239,
  Aspergillus_fruticulosus_CBS_989.72,
  Aspergillus_fumigatiaffinis_CNM-CM6805,
  Aspergillus_fumigatus_Af293,
  Aspergillus_funiculosus_NRRL_4744,
  Aspergillus_germanicus_CBS_123887,
  Aspergillus_glaucus_CBS_516.65,
  Aspergillus_granulosus_CBS_588.65,
  Aspergillus_haitiensis_NRRL_4568,
  Aspergillus_hancockii_FRR_3425,
  Aspergillus_heteromorphus_CBS_117.55,
  Aspergillus_heterothallicus_CBS_489.65,
  Aspergillus_hiratsukae_CNM-CM5793,
  Aspergillus_homomorphus_CBS_101889,
  Aspergillus_hortae_MCA8,
  Aspergillus_ibericus_CBS_121593,
  Aspergillus_incahuasiensis_NRRL_66825,
  Aspergillus_indologenus_CBS_114.80,
  Aspergillus_insuetus_CBS_107.25,
  Aspergillus_intermedius_E25,
  Aspergillus_japonicus_CBS_114.51,
  Aspergillus_jensenii_C4_18042019,
  Aspergillus_karnatakaensis_CBS_102800,
  Aspergillus_kassunensis_NRRL_3752,
  Aspergillus_keveii_CBS_209.92,
  #Aspergillus_latus_MO46169,
  Aspergillus_lentulus_IFM_58399,
  Aspergillus_leporis_CBS_151.66,
  Aspergillus_luchuensis_IFO_4308,
  Aspergillus_lucknowensis_CBS_449.75,
  Aspergillus_melleus_CBS_546.65,
  #Aspergillus_micronesiensis_H39,
  Aspergillus_minisclerotigenes_MRI390,
  Aspergillus_montevidensis_ZYD4,
  Aspergillus_multicolor_CBS_133.54,
  Aspergillus_mulundensis_DSM_5745,
  Aspergillus_nanangensis_MST-FP2251,
  Aspergillus_navahoensis_CBS_351.81,
  Aspergillus_neoniger_CBS_115656,
  Aspergillus_neotritici_S2209,
  Aspergillus_nidulans_FGSC_A4,
  Aspergillus_niger_GCA_000002855,
  Aspergillus_nomiae_NRRL_13137,
  Aspergillus_novofumigatus_IBT_16806,
  Aspergillus_novoparasiticus_CBS_126849,
  Aspergillus_ochraceoroseus_IBT_24754,
  Aspergillus_ochraceus_fc-1,
  Aspergillus_oerlinghausenensis_CBS_139183,
  #Aspergillus_oleicola_CBS_597.65,
  #Aspergillus_olivimuriae_NRRL_66783,
  Aspergillus_oryzae_RIB40,
  Aspergillus_ostianus_IFST_Aos1,
  Aspergillus_panamensis_NRRL_1786,
  Aspergillus_parasiticus_MRI410,
  Aspergillus_persii_NIBRFGC000004109,
  Aspergillus_phoenicis_ATCC_13157,
  Aspergillus_piperis_CBS_112811,
  Aspergillus_pragensis_LH_A260,
  Aspergillus_proliferans_E30,
  Aspergillus_protuberus_HOSP050413_4_129,
  Aspergillus_pseudocaelatus_CBS_117616,
  Aspergillus_pseudodeflectus_CBS_756.74,
  Aspergillus_pseudoglaucus_E42,
  Aspergillus_pseudonomiae_CBS_119388,
  Aspergillus_pseudotamarii_CBS_117625,
  Aspergillus_pseudoterreus_ATCC_32359,
  Aspergillus_pseudoustus_CBS_123904,
  Aspergillus_pseudoviridinutans_IFM_55266,
  Aspergillus_puulaauensis_MK2,
  Aspergillus_quadricinctus_FKII-L3-BK-DRAB1,
  Aspergillus_quadrilineatus_8,
  Aspergillus_rambellii_SRRC1468,
  Aspergillus_recurvatus_CBS_496.65,
  Aspergillus_ruber_CBS_135680,
  Aspergillus_saccharicola_IBT_36126,
  Aspergillus_saccharolyticus_JOP_1030-1,
  Aspergillus_sclerotialis_CBS_366.77,
  Aspergillus_sclerotiicarbonarius_CBS_121057,
  Aspergillus_sclerotioniger_CBS_115572,
  Aspergillus_sclerotiorum_IFST_Ascl1,
  Aspergillus_sergii_CBS_130017,
  Aspergillus_similis_CBS_293.93,
  Aspergillus_sojae_SMF134,
  Aspergillus_sparsus_NRRL_1933,
  Aspergillus_spectabilis_CBS_429.77A,
  Aspergillus_spinulosporus_5845,
  Aspergillus_stella-maris_CBS_113639,
  Aspergillus_steynii_IBT_23096,
 # Aspergillus_subversicolor_LH_A137, -	Aspergillus subversicolor (fusarium)
  Aspergillus_sydowii_CBS_593.65,
  Aspergillus_taichungensis_IBT_19404,
  Aspergillus_tamarii_TPD11,
  Aspergillus_tanneri_NIH1004,
  Aspergillus_tennesseensis_LH_A417,
  Aspergillus_terreus_NIH2624,
  #Aspergillus_terricola_var._indicus_CBS_952.97,
  #Aspergillus_tetrazonus_CBS_591.65A,
  Aspergillus_texensis_NRRL66858,
  Aspergillus_thermomutatus_HMR_AF_39,
  Aspergillus_toxicus_NRRL66898,
  Aspergillus_transmontanensis_CBS_130015,
  Aspergillus_tubingensis_WU-2223L,
  Aspergillus_turcosus_HMR_AF_23,
  Aspergillus_udagawae_IFM_46973,
  Aspergillus_undulatus_CBS_261.88,
  Aspergillus_unguis_F6_8S_P_4A,
  Aspergillus_ustus_AUSTUSMSU,
  Aspergillus_uvarum_CBS_121591,
  Aspergillus_vadensis_CBS_113365,
  Aspergillus_varians_CBS_505.65,
  Aspergillus_venezuelensis_CBS_868.97,
  Aspergillus_verrucosus_NBRC_115547,
  Aspergillus_versicolor_CBS_583.65,
  Aspergillus_violaceofuscus_CBS_115571,
  Aspergillus_viridinutans_IFM_47045,
  Aspergillus_welwitschiae_CBS_139.54b,
  Aspergillus_wentii_DTO_134E9,
  Aspergillus_westerdijkiae_IBT_35663,

  Aspergillus_nomiae_VU104,
  #Neurospora_intermedia_NRRL2884,
  Penicillium_chrysogenum_IBT_35668
  ]